"""initial_schema

Revision ID: 552a93cdaa62
Revises: 96f81c1ff1b8
Create Date: 2026-05-02 12:45:36.020125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552a93cdaa62'
down_revision: Union[str, Sequence[str], None] = '96f81c1ff1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jingles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cover_art_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('AUTO', 'USER_SESSION', name='playlistkind'), nullable=False),
    sa.Column('owner_label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('LIBRARY', 'JINGLES', name='scankind'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'DONE', 'ERROR', name='scanstatus'), nullable=False),
    sa.Column('tracks_added', sa.Integer(), nullable=False),
    sa.Column('tracks_updated', sa.Integer(), nullable=False),
    sa.Column('tracks_removed', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('cover_art_path', sa.Text(), nullable=True),
    sa.Column('tags_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('audio_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'ERROR', name='analysisstatus'), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index('ix_tracks_artist_album_track', 'tracks', ['artist', 'album', 'track_number'], unique=False)
    op.create_index('ix_tracks_genre', 'tracks', ['genre'], unique=False)
    op.create_index('ix_tracks_year', 'tracks', ['year'], unique=False)
    op.create_table('live_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('jingle_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'PLAYING', 'PLAYED', 'SKIPPED', name='livequeuestate'), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jingle_id'], ['jingles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_queue_state_position', 'live_queue', ['state', 'position'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('jingle_id', sa.Integer(), nullable=True),
    sa.Column('overlay_at_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint('track_id IS NOT NULL OR jingle_id IS NOT NULL', name='ck_playlist_item_has_content'),
    sa.ForeignKeyConstraint(['jingle_id'], ['jingles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiet_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('region', sa.Enum('INTRO', 'OUTRO', name='quietregion'), nullable=False),
    sa.Column('db_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_path', sa.Text(), nullable=False),
    sa.Column('jingles_path', sa.Text(), nullable=False),
    sa.Column('idle_behavior', sa.Enum('AUTO_PLAYLIST', 'RANDOM', 'SILENCE', name='idlebehavior'), nullable=False),
    sa.Column('default_auto_playlist_id', sa.Integer(), nullable=True),
    sa.Column('crossfade_enabled', sa.Boolean(), nullable=False),
    sa.Column('crossfade_duration_ms', sa.Integer(), nullable=False),
    sa.Column('gapless_enabled', sa.Boolean(), nullable=False),
    sa.Column('jingle_duck_db', sa.Float(), nullable=False),
    sa.Column('icecast_buffer_offset_ms', sa.Integer(), nullable=False),
    sa.Column('min_quiet_duration_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['default_auto_playlist_id'], ['playlists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('quiet_passages')
    op.drop_table('playlist_items')
    op.drop_index('ix_live_queue_state_position', table_name='live_queue')
    op.drop_table('live_queue')
    op.drop_index('ix_tracks_year', table_name='tracks')
    op.drop_index('ix_tracks_genre', table_name='tracks')
    op.drop_index('ix_tracks_artist_album_track', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('scan_jobs')
    op.drop_table('playlists')
    op.drop_table('jingles')
    # ### end Alembic commands ###
