export const ADJECTIVES = [
  "acrid", "adroit", "agile", "aglow", "alarming", "alluring", "auspicious",
  "awesome", "bashful", "belligerent", "berserk", "blithe", "bountiful",
  "brave", "bright", "brisk", "brooding", "calamitous", "candid",
  "capricious", "careful", "celestial", "charismatic", "charming", "cheerful",
  "chic", "clarion", "clever", "clumsy", "cognizant", "cold", "compassionate",
  "composed", "concise", "confident", "congenial", "constructive", "cool",
  "courageous", "coy", "crisp", "cruel", "crystalline", "curious", "cute",
  "dainty", "dapper", "daring", "dark", "dauntless", "dazzling", "debonair",
  "decisive", "dedicated", "delicate", "delightful", "desirable", "dexterous",
  "diligent", "discerning", "distant", "divine", "dramatic", "dreary",
  "dry", "dual", "dashing", "earnest", "ebullient", "eclectic", "edgy",
  "efficient", "effervescent", "elate", "elegant", "elevated", "eloquent",
  "elusive", "emerald", "enchanting", "endearing", "energetic", "enigmatic",
  "epic", "equitable", "erudite", "essential", "ethereal", "exalted",
  "exemplary", "exhilarating", "exquisite", "fabulous", "facetious", "faint",
  "fair", "faithful", "fancy", "fantastic", "far-reaching", "fascinating",
  "fast", "fatal", "fawn", "fervent", "fierce", "filthy", "finely", "firm",
  "first", "flamboyant", "flashy", "flawless", "fleet", "flippant", "flowing",
  "fluent", "focused", "fond", "formal", "forthright", "fortuitous", "fortune",
  "frank", "frantic", "free", "fresh", "friendly", "frightening", "frisky",
  "full", "furious", "furiously", "futuristic", "gallant", "gay", "generous",
  "genuine", "gently", "gilded", "glamorous", "gleaming", "glib", "glistening",
  "glittering", "gloomy", "glorious", "glowing", "gorgeous", "graceful",
  "grand", "grandiose", "grateful", "grave", "great", "green", "gregarious",
  "guarded", "guileless", "gushing", "gusty", "halcyon", "handsome", "happy",
  "hard", "hardy", "harmonious", "harsh", "hasty", "hateful", "haughty",
  "heavenly", "hedonistic", "heroic", "high", "hilarious", "holy", "honest",
  "hopeful", "horrid", "hot", "humble", "humorous", "hungry", "hurried",
  "idealistic", "illustrious", "immaculate", "imminent", "immortal", "impish",
  "imposing", "impressive", "impudent", "incomparable", "incongruous",
  "indefatigable", "independent", "indigo", "industrious", "inexorable",
  "infallible", "innate", "inquisitive", "insightful", "insouciant", "intrepid",
  "invincible", "inviolable", "iridescent", "ironclad", "jade", "jaunty",
  "jazzy", "jejune", "jocular", "jocund", "jolly", "jovial", "joyful", "joyous",
  "judicious", "juicy", "jumbo", "jumpy", "juvenile", "keen", "khaki",
  "kindly", "kingly", "kooky", "labyrinthine", "laconi", "lanky", "latent",
  "laughable", "lavish", "lawful", "lax", "legendary", "lenient", "liberal",
  "licentious", "lifted", "light", "lightning", "likable", "limber", "limited",
  "luminous", "lustrous", "luxuriant", "lyrical", "macabre", "macho", "magenta",
  "magical", "magnanimous", "magnificent", "majestic", "malleable", "manly",
  "manuel", "marvelous", "masterful", "matched", "mature", "maverick", "meek",
  "melancholic", "mellifluous", "mercurial", "meritorious", "metallic",
  "mighty", "minut", "mirthful", "modest", "molten", "monarch", "monumental",
  "moonlit", "moral", "morose", "muscular", "mysterious", "mythic", "narrow",
  "nascent", "natal", "nautical", "neat", "nebulous", "needy", "nerve",
  "nervous", "new", "nifty", "nimble", "noble", "nocturnal", "noiseless",
  "norm", "nostalgic", "novel", "nurturing", "nutty", "obliging", "obscure",
  "observant", "obvious", "odd", "odorous", "offbeat", "officious", "ominous",
  "omniscient", "oneiric", "open", "operatic", "opulent", "orange", "ordinary",
  "organ", "original", "ornate", "ornery", "outgoing", "outlandish", "outrageous",
  "outstanding", "oval", "overwhelming", "Pacific", "painful", "pale",
  "palpable", "panoramic", "paradoxical", "paramount", "parched", "parental",
  "passionate", "passive", "patent", "pathological", "patrician",
  "patriotic", "peaceful", "pearly", "pedantic", "peppermint", "peptic",
  "percipient", "perennial", "perfect", "perilous", "peripheral", "perky",
  "permanent", "pernicious", "perpendicular", "perpetual", "perseverant",
  "persistent", "personable", "philosophical", "phlegmatic", "picturesque",
  "piercing", "pink", "pious", "pitched", "placid", "plaintive", "plastic",
  "plausible", "plentiful", "pliable", "plucky", "plush", "poetic", "poignant",
  "polished", "polite", "pollen", "poor", "popular", "portentous", "posh",
  "potent", "practical", "pragmatic", "precious", "precocious", "predominant",
  "preeminent", "preferable", "pregnable", "preposterous", "prerequisite",
  "presidential", "prestigious", "prevalent", "prickly", "primary", "prime",
  "primordial", "princely", "principled", "prior", "pristine", "private",
  "prized", "proactive", "probable", "problematic", "proclaimed", "proclivic",
  "prodigious", "product", "professional", "proficient", "profitable", "profound",
  "progressive", "prolific", "prominent", "promising", "prompt", "pronounce",
  "proper", "prophetic", "proportional", "prosing", "prosperous", "protagonist",
  "protective", "protein", "protestant", "proud", "prove", "proverbial", "provisional",
  "prudent", "psych", "public", "puerile", "pugnacious", "pumped", "punchy",
  "punctual", "pungent", "pure", "purposeful", "pushy", "putrid", "quacky",
  "quaint", "qualified", "qualmish", "quantifiable", "quasi", "queasy",
  "questionable", "quick", "quiet", "quintessential", "quirky", "quixotic",
  "quota", "quotable", "rabid", "racial", "radical", "radioactive", "raffish",
  "rainbow", "rambunctious", "rancorous", "random", "rangy", "rapid", "rapt",
  "rare", "rash", "raspy", "ratty", "raucous", "razor-sharp", "reach",
  "reactionary", "readable", "ready", "real", "realistic", "really", "realm",
  "rebel", "reclusive", "redolent", "redoubtable", "refined", "reflective",
  "refractory", "regal", "regional", "regular", "relatable", "relaxed",
  "relentless", "relevant", "reliable", "reluctant", "remarkable", "remedial",
  "remorseless", "renaissance", "renewed", "renowned", "repaired", "repeatable",
  "repulsive", "requisite", "resolute", "resourceful", "respectable", "resplendent",
  "responsible", "responsive", "restful", "restored", "restrictive", "resultant",
  "resurgent", "reticent", "retro", "revered", "reverent", "reverse", "revolutionary",
  "rewarding", "rhetorical", "rhythmic", "ribald", "rich", "richly", "ridiculous",
  "righteous", "rigid", "rigorous", "ritzy", "robust", "romantic", "roomy",
  "rosy", "rotund", "rough", "rounded", "rousing", "royal", "ruddy", "rude",
  "rueful", "rugged", "ruinous", "ruly", "rumpled", "runic", "runny", "rural",
  "rustic", "rusty", "sable", "sad", "sagacious", "salient", "salty", "salubrious",
  "sanctimonious", "sandy", "sanguine", "sapid", "saporous", "sassy", "satin",
  "saturate", "saucy", "savage", "saavy", "scalding", "scandalous", "scant",
  "scarlet", "scathing", "scenic", "sceptical", "scholarly", "sciential",
  "scintillating", "scornful", "scrappy", "scratchy", "scrawly", "screechy",
  "scruffy", "scrumpy", "sculptural", "seamless", "searching", "searing",
  "seasonable", "secluded", "secretive", "sectarian", "secular", "sedate",
  "seductive", "seedy", "seemly", "seething", "seismic", "seminal", "senior",
  "sensible", "sensual", "sentient", "sentinel", "sentry", "serene", "serpentine",
  "serried", "servile", "settled", "severed", "severity", "sexy", "shabbi",
  "shackled", "shaded", "shadowed", "shady", "shafted", "shaggy", "shaken",
  "shallow", "shameless", "shapely", "shared", "sharp", "shattered", "shaven",
  "sheer", "sheet", "shelf", "shell", "shielded", "shiftless", "shimmering",
  "shimmy", "shining", "shiny", "shipshape", "shivering", "shock", "shoddy",
  "shoeless", "shone", "shook", "shooting", "shopworn", "shore", "short",
  "shortsighted", "shout", "showcase", "showoff", "showy", "shrewd", "shrieking",
  "shrill", "shrimpy", "shrine", "shrouded", "shrunken", "shudder", "shut",
  "shy", "sick", "sighted", "silent", "silky", "silly", "silver", "simple",
  "simplified", "sincere", "sinful", "singular", "sinister", "sinuous", "sisterly",
  "skeletal", "sketchy", "skilled", "skimp", "skinny", "skirt", "skittish",
  "skulduggery", "sky", "slack", "slant", "slapdash", "slash", "slate",
  "sleek", "sleep", "sleepless", "sleepy", "sleet", "sleuth", "sliceable",
  "slick", "slight", "slim", "slimy", "sling", "slip", "slippery", "sloppy",
  "sloshed", "slothful", "slouchy", "slovenly", "slow", "sluggish", "slummy",
  "slushy", "sly", "smack", "small", "smart", "smash", "smashed", "smeary",
  "smell", "smelly", "smile", "smiling", "smirk", "smith", "smock", "smoggy",
  "smoke", "smoky", "smooth", "smother", "smudge", "smudgy", "smug", "snack",
  "snafu", "snaggly", "snappy", "snare", "snarly", "sneaky", "sneer", "sneeze",
  "snide", "sniff", "sniffly", "snippy", "snit", "snitch", "snobby", "snoop",
  "snoopy", "snooty", "snotty", "snout", "snow", "snowy", "snub", "snuck",
  "snuff", "snug", "snuggle", "soaked", "soapy", "soaring", "sober", "social",
  "sock", "sodden", "soft", "soggy", "solar", "soldierly", "solid", "solitary",
  "somnolent", "sonic", "soothed", "soothing", "sophisticated", "sordid",
  "sore", "sorrowful", "sorry", "sorted", "soulful", "sound", "soup", "soupy",
  "sour", "source", "south", "southern", "spacious", "spare", "spark", "sparkle",
  "sparkling", "sparingly", "sparse", "spasmodic", "spastic", "spatial", "spatter",
  "spawn", "speak", "spear", "special", "speci", "specific", "specimen",
  "speck", "speckled", "spectacular", "specter", "sped", "speechless", "speed",
  "speedy", "spell", "spellbound", "spend", "spent", "spherical", "spice",
  "spicy", "spider", "spiffy", "spike", "spiky", "spill", "spin", "spindly",
  "spine", "spiral", "spirited", "spiteful", "splash", "splashy", "splatter",
  "splendid", "splinter", "split", "spoil", "spoke", "spoken", "spongy",
  "sponsor", "spook", "spooky", "spool", "spoon", "sporadic", "sport", "sporting",
  "sportive", "spotless", "spotted", "spotty", "spouse", "spout", "sprain",
  "sprawl", "sprawling", "spread", "spree", "spring", "springy",
  "sprint", "sprite", "spruce", "spry", "spud", "spun", "spunk", "spunky",
  "spurious", "spurned", "spurt", "spy", "squad", "squared", "squash", "squat",
  "squawk", "squeak", "squeaky", "squeal", "squeamish", "squeeze", "squid",
  "squire", "squirm", "squirmy", "squirrel", "squirt", "stab", "stable",
  "stack", "staff", "stage", "staid", "stain", "stained", "stair", "stake",
  "stalactite", "stalagmite", "stale", "stalk", "stall", "stamp", "stance",
  "stand", "standard", "stank", "staple", "star", "starch", "stardom",
  "stark", "start", "startled", "startling", "startup", "starved", "starving",
  "state", "stationary", "statuesque", "status", "staunch", "stave", "stay",
  "steadfast", "steady", "steak", "steal", "stealth", "stealthy", "steam",
  "steamy", "steel", "steep", "steer", "stellar", "stem", "stench", "stencil",
  "step", "stereo", "stern", "stew", "stick", "sticky", "stiff", "stifle",
  "stigma", "still", "stilted", "sting", "stinging", "stingy", "stink",
  "stinky", "stint", "stipend", "stipple", "stir", "stock", "stocking",
  "stoic", "stoke", "stolen", "stomp", "stone", "stony", "stood", "stool",
  "stoop", "stop", "store", "stork", "storm", "stormy", "story", "stout",
  "stove", "stow", "strain", "strait", "strand", "strange", "stranger",
  "strangle", "strap", "strata", "straw", "stray", "streak", "streaked",
  "stream", "streamlined", "street", "strength", "stress", "stretch", "strewn",
  "strict", "stride", "strident", "strife", "strike", "string", "stringy",
  "strip", "stripe", "striped", "strive", "strobe", "stroke", "stroll",
  "strong", "struck", "structural", "struggle", "strumpet", "strut", "stub",
  "stubble", "stubborn", "stuck", "stud", "student", "studio", "studious",
  "study", "stuff", "stuffed", "stuffy", "stumble", "stump", "stun", "stung",
  "stunk", "stunning", "stunt", "stupid", "sturdy", "style", "stylish",
  "suave", "sub", "subject", "submit", "subordinate", "subsequent", "subservient",
  "subside", "substantial", "substantiate", "subtle", "suburb", "suburban",
  "subvert", "success", "successful", "succinct", "succulent", "such", "suck",
  "sudden", "sue", "suffer", "suffice", "sugar", "sugary", "suggest", "suicide",
  "suit", "suite", "suited", "sulk", "sulky", "sultan", "sum", "summary",
  "summer", "summit", "summon", "sun", "sung", "sunk", "sunken", "sunny",
  "super", "superb", "superficial", "superfluous", "superhero", "superior",
  "supernatural", "superstitious", "supple", "supplement", "supply", "support",
  "suppose", "suppress", "supreme", "sure", "surely", "surface", "surge",
  "surgeon", "surgery", "surly", "surmise", "surmount", "surname", "surpass",
  "surplus", "surprise", "surprised", "surprising", "surreal", "surrender",
  "surround", "survey", "survive", "susceptible", "suspect", "suspend",
  "suspense", "suspicion", "suspicious", "sustain", "svelte", "swagger",
  "swamp", "swampy", "swan", "swank", "swanlike", "swap", "swarm", "swarthy",
  "swat", "sway", "swear", "swearword", "sweat", "sweater", "sweaty", "sweep",
  "sweet", "swell", "sweltering", "swept", "swerve", "swift", "swim", "swindle",
  "swine", "swing", "swipe", "swirl", "swirly", "swiss", "switch", "swivel",
  "swollen", "swoon", "swoop", "sword", "swore", "sworn", "swum", "swung",
  "symbolic", "sympathetic", "symptom", "syndrome", "synergy", "synopsis",
  "syntax", "system", "table", "taboo", "tacit", "tack", "tackle", "tacky",
  "tact", "tactful", "tactless", "tadpole", "tag", "tail", "tailor", "taint",
  "take", "taken", "tale", "talent", "talisman", "talk", "tall", "tally",
  "tame", "tang", "tangible", "tangle", "tangled", "tank", "tanker", "tap",
  "tape", "tar", "tardy", "tariff", "tarnish", "tarp", "tarry", "tart",
  "task", "tassel", "taste", "tasteful", "taster", "tasting", "tasty",
  "tat", "tatter", "tattered", "tattoo", "taunt", "tavern", "tax", "taxi",
  "taxicab", "tea", "teach", "teacher", "team", "tear", "tease", "technical",
  "technique", "tedious", "tedium", "teen", "teens", "telephone", "telescope",
  "tell", "temper", "temperate", "tempest", "temple", "tempo", "temporary",
  "tempt", "ten", "tenant", "tend", "tendency", "tender", "tendon", "tennis",
  "tense", "tension", "tent", "tenth", "tepid", "term", "terminal", "terms",
  "tern", "terrain", "terrible", "terrific", "terrified", "terrify", "territory",
  "terror", "test", "testify", "testimony", "text", "textbook", "texture",
  "than", "thank", "that", "thaw", "theater", "theft", "their", "them",
  "theme", "then", "theory", "therapy", "there", "thereabout", "thereafter",
  "thereby", "thermal", "these", "thesis", "they", "thick", "thicken",
  "thief", "thigh", "thin", "thing", "think", "third", "thirst", "thirsty",
  "thirteen", "this", "thong", "thorn", "thorny", "thorough", "those",
  "though", "thought", "thousand", "thrash", "thread", "threat", "threaten",
  "three", "thresh", "threshold", "thrift", "thrifty", "thrill", "thrilling",
  "thrive", "throat", "throb", "throne", "throng", "through", "throw", "thrust",
  "thud", "thug", "thumb", "thump", "thunder", "thus", "thwart", "tick",
  "ticket", "tickle", "tidal", "tide", "tidy", "tier", "tiger", "tight",
  "tile", "till", "tilt", "timber", "time", "timely", "timeout", "timid",
  "tinge", "tingle", "tinker", "tint", "tiny", "tip", "tipoff", "tissue",
  "title", "to", "toad", "toast", "today", "toddle", "toddler", "toe",
  "toenail", "together", "toil", "token", "told", "toll", "tomato", "tomb",
  "tomorrow", "ton", "tone", "tongs", "tongue", "tonic", "tonight", "tool",
  "toot", "tooth", "toothsome", "top", "topic", "torch", "tore", "torment",
  "torn", "tornado", "torpedo", "torrent", "torso", "tortoise", "torture",
  "toss", "total", "totally", "totter", "touch", "touched", "touching",
  "touchy", "tough", "tour", "tourist", "tousle", "tout", "tow", "toward",
  "tower", "town", "toxic", "toxin", "trace", "track", "tract", "trade",
  "trader", "tradition", "traffic", "tragedy", "tragic", "trail", "trailer",
  "train", "trait", "traitor", "tramp", "trample", "trance", "tranquil",
  "trap", "trash", "trauma", "trawl", "tray", "treacherous", "tread", "treason",
  "treasure", "treat", "treaty", "tree", "trek", "tremble", "tremendous",
  "trench", "trend", "trendy", "trial", "triangle", "tribal", "tribe",
  "tribute", "trick", "tricky", "tried", "trifle", "trigger", "trillion",
  "trim", "trinity", "trio", "trip", "triple", "triumph", "trivial", "trod",
  "troll", "troop", "trophy", "tropical", "trot", "trouble", "troublesome",
  "trough", "trout", "truce", "truck", "trudge", "true", "truly", "trump",
  "trumpet", "trunk", "trust", "trusted", "trustworthy", "trusty", "truth",
  "truthful", "try", "tub", "tube", "tuck", "tuesday", "tug", "tuition",
  "tulip", "tumble", "tumor", "tumult", "tuna", "tundra", "tune", "tunnel",
  "turban", "turf", "turkey", "turn", "turnip", "turret", "turtle", "tutor",
  "tuxedo", "twang", "tweak", "tweed", "tweet", "twelve", "twenty", "twice",
  "twig", "twilight", "twine", "twinge", "twinkle", "twirl", "twist", "twisted",
  "twister", "twitch", "two", "type", "typical", "typist", "tyrant", "udder",
  "ugly", "ulcer", "ultimate", "ultimatum", "ultra", "umber", "umbrella",
  "umpire", "unable", "unaccountable", "unaware", "unbiased", "uncle", "under",
  "undergo", "undermine", "underneath", "understood", "undertake", "undo",
  "undone", "unemployed", "uneven", "unexpected", "unfair", "unfold", "unfortunate",
  "unfriend", "ungainly", "unhappy", "unhealthy", "unheard", "unheard-of",
  "unicorn", "uniform", "unify", "union", "unique", "unit", "unite", "unity",
  "unkempt", "unknown", "unless", "unlike", "unlikely", "unload", "unlock",
  "unlucky", "unpack", "unpaid", "unprepared", "unreal", "unreasonable",
  "unrest", "unruly", "unsafe", "unsaid", "unseen", "unsightly", "unsteady",
  "unsuccessful", "until", "untold", "untrue", "unused", "unusual", "unveil",
  "unwary", "unwell", "unwieldy", "unwind", "unwise", "unwrap", "upbeat",
  "update", "upgrade", "uphill", "uphold", "upon", "upper", "uproar", "uproot",
  "upset", "upside", "uptake", "uptown", "upward", "urban", "urge", "urgent",
  "urine", "us", "usage", "use", "used", "useful", "useless", "user", "usher",
  "usual", "usually", "utensil", "utility", "utmost", "utter", "uttermost",
  "vacant", "vacuum", "vague", "vain", "valet", "valid", "valley", "valor",
  "value", "valve", "van", "vandal", "vanguard", "vanilla", "vanish", "vanity",
  "vapor", "varied", "variety", "various", "varnish", "vary", "vase", "vast",
  "vastly", "vault", "veer", "veil", "veiled", "vein", "velvet", "velvety",
  "vendor", "veneer", "venom", "vent", "venture", "venue", "verb", "verdict",
  "verdure", "verge", "verify", "verse", "version", "versus", "very", "vessel",
  "vest", "vet", "veteran", "veto", "vex", "vibrate", "vice", "vicious",
  "victim", "victor", "victory", "video", "view", "vigil", "vigor", "vile",
  "village", "villain", "vine", "vintage", "violate", "violence", "violent",
  "violet", "violin", "viper", "viral", "virgin", "virtual", "virtue", "virus",
  "visa", "visible", "vision", "visit", "visitor", "visor", "visual", "vital",
  "vivid", "vocal", "vodka", "vogue", "voice", "void", "volt", "voltage",
  "volume", "vomit", "vote", "voter", "vouch", "voucher", "vow", "vowel",
  "voyage", "vulgar", "wade", "wag", "wage", "wagon", "waif", "wail", "waist",
  "wait", "waiter", "wake", "waken", "walk", "wall", "wallet", "walnut",
  "walrus", "wampum", "wan", "wand", "wander", "wane", "want", "war", "ward",
  "wardrobe", "warehouse", "warm", "warmth", "warn", "warning", "warp", "warrant",
  "warrior", "wart", "wary", "was", "wash", "washer", "wasp", "waste", "wasted",
  "watch", "water", "waterfall", "waterlogged", "watery", "watt", "wave",
  "waver", "wavy", "wax", "way", "we", "weak", "weaken", "wealth", "wealthy",
  "wean", "weapon", "wear", "weary", "weasel", "weather", "weave", "web",
  "wed", "wedding", "wedge", "wee", "weed", "weedy", "week", "weekday", "weekend",
  "weekly", "weep", "weigh", "weight", "weird", "welcome", "welfare", "well",
  "went", "wept", "were", "west", "western", "wet", "whack", "whale", "whaler",
  "wharf", "what", "wheat", "wheel", "wheeze", "when", "where", "whereas",
  "whereby", "wherever", "whether", "whey", "which", "whiff", "while", "whim",
  "whimper", "whimsy", "whine", "whip", "whir", "whirl", "whirlpool", "whirlwind",
  "whisk", "whisker", "whiskey", "whisper", "whistle", "white", "whiten",
  "whole", "wholly", "whom", "whose", "wicked", "wide", "widen", "widow",
  "width", "wield", "wife", "wiggle", "wild", "wildly", "will", "willful",
  "willing", "willow", "wilt", "wily", "wimp", "win", "wince", "winch",
  "wind", "window", "windy", "wine", "wing", "wink", "winner", "winter",
  "wipe", "wire", "wired", "wiry", "wisdom", "wise", "wisely", "wish", "wisp",
  "wit", "witch", "with", "wither", "within", "without", "witness", "witty",
  "wizard", "woe", "woken", "wolf", "woman", "womanly", "wonder", "wonderful",
  "woo", "wood", "wooded", "wooden", "woods", "woody", "wool", "woolen",
  "woolly", "word", "wordy", "work", "worker", "workout", "workshop", "world",
  "worm", "wormy", "worn", "worried", "worse", "worsen", "worship", "worst",
  "worth", "worthless", "worthwhile", "worthy", "would", "wound", "wove",
  "woven", "wrack", "wrath", "wreath", "wreck", "wrench", "wrest", "wrestle",
  "wretch", "wriggle", "wring", "wrinkle", "wrist", "writ", "write", "writer",
  "writhe", "written", "wrong", "wrote", "wrought", "wrung", "yacht", "yak",
  "yam", "yank", "yap", "yard", "yarn", "yawn", "year", "yearly", "yearn",
  "yeast", "yell", "yellow", "yelp", "yes", "yesterday", "yet", "yield",
  "yodel", "yoga", "yoke", "yolk", "yonder", "you", "young", "youngster",
  "your", "yours", "yourself", "youth", "youthful", "zany", "zeal", "zealot",
  "zealous", "zebra", "zenith", "zephyr", "zero", "zest", "zesty", "zigzag",
  "zinc", "zip", "zipper", "zippy", "zodiac", "zombie", "zone", "zany", "zen",
  "zero", "zephyr", "zigzag", "zippy", "zone", "zoo", "zoom",
];

export const SCIENTISTS = [
  "Ampere", "Archimedes", "Aristotle", "Bacon", "Bell", "Bohr", "Boltzmann",
  "Born", "Bose", "Brahmagupta", "Broglie", "Cantor", "Capac", "Cauchy",
  "Chandrasekhar", "Copernicus", "Curie", "Darwin", "deBroglie", "Descartes",
  "Dewdney", "Dicke", "Dirac", "Eckert", "Edison", "Einstein", "Euler",
  "Fahrenheit", "Faraday", "Fermi", "Feynman", "Fisher", "Fleming", "Fowler",
  "Franklin", "Galileo", "Galois", "Gamow", "Gauss", "Gell-Mann", "Germain",
  "Goeppert", "Godel", "Goldberg", "Goldstein", "Golgi", "Gupta", "Hahn",
  "Harrison", "Hawking", "Heisenberg", "Helmholtz", "Henderson", "Henry",
  "Hertz", "Hilbert", "Hipparchus", "Hooke", "Hoyle", "Hubble",
  "Huygens", "Jensen", "Julius", "Kekule", "Kepler", "Kerr", "Kirchhoff",
  "Klein", "Kronecker", "Koch", "Kolmogorov", "Kramers", "Kuiper",
  "Lagrange", "Lambert", "Landau", "Landsteiner", "Laplace", "Latimer",
  "Laughlin", "Lawrence", "Leavitt", "Lee", "Lemaître", "Lewis",
  "Linde", "Lobachevsky", "Lorentz", "Mach", "MacLane", "Mandelbrot",
  "Mandel", "Maxwell", "Mayer", "McMillan", "Mendel", "Mendeleev", "Mills",
  "Möbius", "Morse", "Mössbauer", "Navier", "Nelson", "Neumann", "Newton",
  "Nietzsche", "Noether", "Oersted", "Onsager", "Oppenheimer",
  "Pascal", "Pauli", "Peierls", "Planck", "Poincare", "Poisson", "Pythagoras",
  "Raman", "Rayleigh", "Reines", "Rutherford", "Rydberg", "Schrodinger",
  "Schwartz", "Seaborg", "Segrè", "Shockley", "Siegel", "Smoot", "Stone",
  "Strauss", "Taylor", "Thales", "Thomson", "Townes", "Turing", "Urey",
  "Van der Waals", "van Leeuwenhoek", "van Vleck", "von Braun", "von Neumann",
  "Waring", "Weinberg", "Weiss", "Weisskopf", "Weyl", "Wheeler", "Wien",
  "Wilczek", "Wigner", "Wilson", "Woese", "Wu", "Zel'dovich", "Zwicky",
];

export function generateName(): string {
  const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const scientist = SCIENTISTS[Math.floor(Math.random() * SCIENTISTS.length)];
  return `${adj}_${scientist}`;
}